title: Revista Sitio
email: hdlabconicet@gmail.com
description: (1982-2026)
baseurl: "/revista-sitio-digital"
url: "https://hdlab.space"
github_repo: revista-sitio-digital/
twitter_username: hdlabconicet
github_username:  hdlabconicet
facebook_username: hdlabconicet

social_link: twitter
social_username: hdlabconicet

theme_color: light

# Build settings
markdown: kramdown

collections:
    pages:
      output: true
    recursos:
      output: true
    txtxpagina:
      output: true
